[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
gas_reports = ["*"]
via_ir = true
optimizer = true
optimizer_runs = 20000
fs_permissions = [
    { access = "read", path = "lib/foundry-chainlink-toolkit/out" },
]

[rpc_endpoints]
fuji = "https://api.avax-test.network/ext/bc/C/rpc"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
